"""Rename department to departments

Revision ID: 98638f167b65
Revises: 2372e52f067b
Create Date: 2024-04-03 16:29:49.899780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98638f167b65'
down_revision = '2372e52f067b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
